services:
  searchingservicepocc:
    build:
      context: .
      dockerfile: SearchingService POC c#/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5217
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false  
      - ASPNETCORE_URLS=http://+:5217
    ports:
      - "5217:5217"
